In [1]:
# imports
import copy
import time
from numpy.random import randint

In [2]:
# http://interactivepython.org/runestone/static/pythonds/SortSearch/TheBubbleSort.html
def bubbleSort(alist):
    for passnum in range(len(alist)-1,0,-1):
        for i in range(passnum):
            if alist[i]>alist[i+1]:
                temp = alist[i]
                alist[i] = alist[i+1]
                alist[i+1] = temp
totalRunTime = 0

for i in range(0,10):
	size10 = randint(0,10,10)
	print(size10)
	start_time = time.time()
	bubbleSort(size10)
	end_time = time.time()
	currentRunTime = end_time - start_time
	print(currentRunTime)
	print(size10)
	totalRunTime += currentRunTime
print("*******************************")	
averageRunTime = totalRunTime/10
print(averageRunTime)

[3 3 8 3 2 0 2 9 5 7]
0.0
[0 2 2 3 3 3 5 7 8 9]
[9 0 7 4 9 8 6 7 7 7]
0.0
[0 4 6 7 7 7 7 8 9 9]
[6 4 5 5 1 6 0 5 9 0]
0.0
[0 0 1 4 5 5 5 6 6 9]
[7 0 6 2 6 0 3 8 1 1]
0.0
[0 0 1 1 2 3 6 6 7 8]
[7 6 9 0 1 6 1 5 3 6]
0.0
[0 1 1 3 5 6 6 6 7 9]
[6 0 0 2 7 6 2 0 6 3]
0.0
[0 0 0 2 2 3 6 6 6 7]
[7 7 2 3 9 2 7 0 4 9]
0.0
[0 2 2 3 4 7 7 7 9 9]
[6 7 3 9 4 3 5 7 0 0]
0.0
[0 0 3 3 4 5 6 7 7 9]
[9 4 5 7 3 5 0 6 2 4]
0.0
[0 2 3 4 4 5 5 6 7 9]
[0 2 1 3 7 1 2 2 1 9]
0.0
[0 1 1 1 2 2 2 3 7 9]
*******************************
0.0
